apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: dev
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
  - hosts:
    - ./*
    - observability/*
    - istio-system/*
