apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fastify
  namespace: dev
spec:
  selector:
    matchLabels:
      run: app-fastify
  replicas: 1
  template:
    metadata:
      labels:
        run: app-fastify
    spec:
      containers:
      - name: app-fastify
        image: rccsilva/app-fastify:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: ELASTIC_APM_SERVICE_NAME
            value: app-fastify
          - name: ELASTIC_APM_SERVER_URL
            value: http://apm.observability.svc:8200
          - name: ELASTIC_APM_VERIFY_SERVER_CERT
            value: "false"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-fastify
  namespace: dev
  labels:
    run: app-fastify
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: app-fastify
