apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-express-opentelemetry
  namespace: dev
spec:
  selector:
    matchLabels:
      run: app-express-opentelemetry
  replicas: 1
  template:
    metadata:
      labels:
        run: app-express-opentelemetry
    spec:
      containers:
        - name: app-express-opentelemetry
          image: rccsilva/app-express-opentelemetry:latest
          imagePullPolicy: Never
          env:
            - name: HOST_OTPL_COLLECTOR
              value: http://collector-collector-headless.observability.svc:4318
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-express-opentelemetry
  namespace: dev
  labels:
    run: app-express-opentelemetry
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    run: app-express-opentelemetry
