env:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-es-elastic-user
        key: elastic

config:
  inputs: |
    [INPUT]
        name            node_exporter_metrics
        tag             node_metrics
        scrape_interval 2
    [INPUT]
        name              tail
        path              /var/log/containers/*.log
        Tag               kube.*
        multiline.parser  docker, cri
  outputs: |
    [OUTPUT]
        Name        es
        Match       kube.*
        Host        elasticsearch-es-default.observability.svc
        Port        9200
        Index       logs-fluent_bit-kube-default
        tls         On
        tls.verify  Off
        HTTP_User   elastic
        HTTP_Passwd ${ELASTIC_PASSWORD}
        Suppress_Type_Name On
    [OUTPUT]
        Name        stdout
        Match       node_metrics
